spring.datasource.url=jdbc:sqlserver://NTB005093\\SQLEXPRESS:1433;databaseName=ergpro;sslProtocol=TLS;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=erg102030@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create


#Config MyBatis
mybatis.mapper-locations=classpath*:mappers/**/*.xml
mybatis.type-aliases-package=com.ergproapontamento.ergpro.query
mybatis.configuration.map-underscore-to-camel-case=true

#Config token
api.security.token.secret=${JWT_SECRET:my-secret-key}



